### ISSUE TITLE
The Behaviour module is deprecated in Elixir 1.4.4

### ISSUE THREAD

**Issue by tianjianyong** [rmies/monad#13]
mix deps.compile monad
==> monad
Compiling 6 files (.ex)
warning: the Behaviour module is deprecated. Instead of using this module, use the @callback and @macrocallback module attributes. See the documentation for Module for more information on these attributes
  lib/monad/writer.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:71: :elixir_module.do_compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

warning: the Behaviour module is deprecated. Instead of using this module, use the @callback and @macrocallback module attributes. See the documentation for Module for more information on these attributes
  lib/monad.ex:2: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:71: :elixir_module.do_compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

warning: the Behaviour module is deprecated. Instead of using this module, use the @callback and @macrocallback module attributes. See the documentation for Module for more information on these attributes
  lib/monad.ex:231: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:191: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:71: :elixir_module.do_compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

Generated monad app

**Comment by luc-tielen** [comment]
This should be fixed now that my PR is merged.. can be closed?
(Double-check just in case..)
