### ISSUE TITLE
Compiler warnings on Elixir 1.1

### ISSUE THREAD

**Issue by dantswain** [rmies/monad#7]
When compiling on Elixir 1.1, I get compiler warnings:

```
warning: the underscored variable "_monad_pipebind_arg" is used after being set. A leading underscore indicates that the value of the variable should be ignored. If this is intended please rename the variable to remove the underscore
```

It seems to originate here: https://github.com/rmies/monad/blob/597a7dbaa601558058dd5861466e5240a5badbaa/lib/monad.ex#L268

```
          {bind(unquote(elem(x, 0)), fn _monad_pipebind_arg ->
            unquote(Macro.pipe(quote do _monad_pipebind_arg end, elem(fc, 0), 0))
           end), 0}
```

Removing the leading underscore should resolve it.  I'd be glad to submit a PR if it would help.

**Comment by rmies** [comment]
Yes, please do submit a PR.
